### ISSUE TITLE
Erro para mostrar free shipping from value

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-custom-shipping#5]
Na loja https://www.jamalsuplementos.com.br/ tem algumas regras de frete personalizado, porém duas com frete grátis, uma de retirada na loja e outra de frete grátis a partir de 199 (duas transportadoras diferentes). Na regra de retirada na loja, foi configurado `disable_free_shipping_from`: `true` e na outra de frete grátis em pedidos de no mínimo 199 como `false` para mostrar o card.

Ao fazer o teste na loja, a resposta da API, vem corretamente com o parâmetro:

`free_shipping_from_value`: `199`

Porém no checkout, não mostra a informação que faltam x reais para frete grátis

**Comment by leomp12** [comment]
Pelo que entendi o app retorna certo, se é esse o caso não tem issue aqui, se realmente houver um erro (não tenho certeza se entendi) é do checkout no Storefront.
