### ISSUE TITLE
Configuração rápida erro com cep de origem

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-custom-shipping#6]
Se é realizado uma configuração rápida, colocando cep de origem na regra apenas, a mesma não funciona. Somente se colocar o cep de origem na aba **Geral**. Porém com a **configuração rápida** o cep da aba geral fica escondida e ninguém vê

**Comment by leomp12** [comment]
Um exemplo do data que deu erro? Ou o Store ID pra eu ver...

**Comment by matheusgnreis** [comment]
Loja de teste 1606 - https://alternativacalcados.netlify.app/teste---planner-personalizado-sem-data
